services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: clientes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "clientes_db"]
      interval: 5s
      retries: 12
      timeout: 5s

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
    command: ["node", "dist/server.js"]

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production

volumes:
  postgres_data:
